FROM golang:1.17.2-alpine
RUN mkdir /app
ADD docker /app
WORKDIR /app
COPY . /app/
RUN apk add git libc-dev gcc vim && go mod tidy
RUN CGO_ENABLED=1 GO111MODULE=on go build -tags=jsoniter -a -o ohlcv
CMD ["/app/ohlcv"]
