---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    deploymentTime: {{ now | date "2006-01-02T15:04:05" }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: {{ .Values.service.protocol }}
    - port: {{ .Values.service.port_grpc }}
      name: grpc
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
