apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ohlcv
spec:
  selector:
    matchLabels:
      app: ohlcv
  replicas: 1
  template:
    metadata:
      labels:
        app: ohlcv
    spec:
      containers:
        - name: ohlcv
          image: $ECR_PATH:ohlcv-$VERSION
          env:
            - name: KAFKA_HOST
              value: "$KAFKA_HOST"
            - name: KAFKA_SSL
              value: "$KAFKA_SSL"
            - name: KAFKA_SUBSCRIBER_COUNT
              value: "$KAFKA_SUBSCRIBER_COUNT"
            - name: KAFKA_TOPIC_PREFIX
              value: "$KAFKA_TOPIC_PREFIX"
            - name: LOG_LEVEL
              value: "$LOG_LEVEL"
            - name: SERVICE_NAME
              value: "$SERVICE_NAME"
            - name: MONGODB_URL
              value: "$MONGODB_URL"
            - name: MONGODB_DEAL_COLLECTION_NAME
              value: "$MONGODB_DEAL_COLLECTION_NAME"
            - name: MONGODB_MINUTE_CANDLE_COLLECTION_NAME
              value: "$MONGODB_MINUTE_CANDLE_COLLECTION_NAME"
            - name: CENTRIFUGE_HOST
              value: "$CENTRIFUGE_HOST"
            - name: CENTRIFUGE_TOKEN
              value: "$CENTRIFUGE_TOKEN"
            - name: EXCHANGE_MARKETS_SERVER_URL
              value: "$EXCHANGE_MARKETS_SERVER_URL"
            - name: EXCHANGE_MARKETS_TOKEN
              value: "$EXCHANGE_MARKETS_TOKEN"
---
apiVersion: v1
kind: Service
metadata:
  name: ohlcv
  labels:
    app: ohlcv
spec:
  ports:
    - port: 8082
      name: tcp-8082
  selector:
    app: ohlcv
